// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh9epUVNmoZNQH9Xi4BwsjA6usmYQCll8',
    appId: '1:481372574044:web:9731ff10b9a4f584a3b199',
    messagingSenderId: '481372574044',
    projectId: 'vetsistema-9f5c3',
    authDomain: 'vetsistema-9f5c3.firebaseapp.com',
    storageBucket: 'vetsistema-9f5c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuU96b__vEqDIfratqWbI4HiyWBLWjHvE',
    appId: '1:481372574044:android:8af7b833b7740cbfa3b199',
    messagingSenderId: '481372574044',
    projectId: 'vetsistema-9f5c3',
    storageBucket: 'vetsistema-9f5c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEbA1cpZYvMscYlhgd1fBaZ4o2oenEGhw',
    appId: '1:481372574044:ios:b320f15d718ffcf3a3b199',
    messagingSenderId: '481372574044',
    projectId: 'vetsistema-9f5c3',
    storageBucket: 'vetsistema-9f5c3.appspot.com',
    iosBundleId: 'com.example.vetsistema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEbA1cpZYvMscYlhgd1fBaZ4o2oenEGhw',
    appId: '1:481372574044:ios:d414d11ddc69f95fa3b199',
    messagingSenderId: '481372574044',
    projectId: 'vetsistema-9f5c3',
    storageBucket: 'vetsistema-9f5c3.appspot.com',
    iosBundleId: 'com.example.vetsistema.RunnerTests',
  );
}
